version: "3"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12.4-management
